name: Update Design System Index
on:
  push:
    branches: [main]
    paths:
      - "components/**"

jobs:
  index-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Index repository components
        run: npx "@builder.io/dev-tools@latest" index-repo --skipHeader --designSystemName builder-sandbox
        env:
          BUILDER_PUBLIC_KEY: ${{ secrets.BUILDER_PUBLIC_KEY }}
          BUILDER_PRIVATE_KEY: ${{ secrets.BUILDER_PRIVATE_KEY }}
          BUILDER_USER_ID: ${{ secrets.BUILDER_USER_ID}}
